[workspace]
resolver = "2"
members = ["fly-machines-gen", "peristera"]

[workspace.package]
authors = ["Abhi Agarwal <abhiaagarwal01@gmail.com>"]
license = "MIT OR Apache-2.0"
edition = "2021"
repository = "https://github.com/abhiaagarwal/peristera"
